### PR TITLE
Add .browserslistrc file

### PR DESCRIPTION
**Pull request by ataylorme**
Use `.browserslistrc` instead of definitions in `package.json` and `config/themeConfig.js` for browser lists.

## Description

Addresses issue #105

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ataylorme** [comment]
There was a `browserslist` definition in `package.json` I had to delete in order for [`postcss-preset-env`](https://www.npmjs.com/package/postcss-preset-env) to read `.browserslistrc`. I wasn't able to find where that definition in `package.json` was being used. @mor10 @bamadesigner @felixarntz do you have an idea? I just want to make sure removing it won't break anything (the build process stil ran fine for me).

**Comment by mor10** [comment]
The code in package.json was there from earlier. It makes sense to move it to a dedicated file. I think json settings override .browserlistrc settings.

From my recollection, the list is used by Babel, stylelint, and PostCSS, all of which should pick up the settings from .browserlistrc automatically.

Can't test because I'm 🛫

**Comment by bamadesigner** [comment]
Potential merge conflict with #233.

**Comment by ataylorme** [comment]
@bamadesigner I updated both README files. Is there a reason the two files differ in content? I bet we could make a gulp process that auto-generates `readme.txt` from `README.md`

**Comment by mor10** [comment]
There's another ticket /PR in here somewhere addressing README.md. we have to consider context here: for WP Rig, readme needs to be about the project. For people using WP Rig, readme needs to be about their project.

**Comment by ataylorme** [comment]
Since we will address readme discrepencies elsewhere I think this PR is ready to go

**Comment by bamadesigner** [comment]
I'm good to merge. @mor10?

**Pull request merged**
