### PR TITLE
Let backslashToForwardSlash handle arrays of paths

### PR DESCRIPTION
**Pull request by prikkprikkprikk**
## Description

Addresses issue #498

I got an error when running npm run dev:

`TypeError: path.replace is not a function`

Turns out the function sometimes receives arrays of paths, so I added support for that.

Also made the replacement into an arrow function to avoid repetition of code.

(Please go easy on me, this is my first pull request on GitHub!)

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by GitaStreet** [comment]
Well done! 

Not only did it fix that issue on my Windows 10.

It also solved previous issues I had with BrowserSync only running once after a file edit.

**Comment by ataylorme** [comment]
@prikkprikkprikk thank you for the pull request and @GitaStreet thank you for testing this!

> It also solved previous issues I had with BrowserSync only running once after a file edit.

I think that was solved by #493 but glad to have this additional fix as well.

**Comment by ataylorme** [comment]
@mor10 can you test this and give another approval? Then we can merge.

**Comment by ataylorme** [comment]
> Please go easy on me, this is my first pull request on GitHub

@prikkprikkprikk you did great! The pull request is much appreciated.

**Pull request merged**
