### PR TITLE
Ensure that the theme requirements are met, otherwise bail and warn the user

### PR DESCRIPTION
**Pull request by ataylorme**
## Description
An update of #59 for `v1.1`. Addresses #50

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by felixarntz** [comment]
@ataylorme Thanks for proceeding with and incorporating this. Looks good to me, just a merge conflict to resolve. It would be good to re-copy all respective functions out of `functions.php` to the new files in `/inc`, in case they have changed in the meantime. Just to make sure.

**Comment by ataylorme** [comment]
@felixarntz I'll add you to my fork in case you can get to the merge conflict resolution and `functions.php` update before I can. I was traveling last week and am packing/moving this week so I probably won't be able to circle back around to this for a while.

**Comment by felixarntz** [comment]
Fixed the merge conflict. This is ready IMO.

**Comment by mor10** [comment]
Sorry. I made a bunch of merges to the main branch before I noticed this one. Can you update to resolve the new conflicts and I'll merge it?

**Comment by felixarntz** [comment]
@mor10 Done!

**Comment by mor10** [comment]
ugh. sorry. one more refresh is needed 😬

**Comment by felixarntz** [comment]
@mor10 Done, once again. Can you please merge this, otherwise people will be creating PRs on and on modifying `functions.php`, and it will never get in. 😄

**Comment by mor10** [comment]
I'll merge it as soon as I get home.

**Comment by mor10** [comment]
Merged. Sorry for the delay and repeated requests for updates.

**Pull request merged**
