### PR TITLE
Automatically transform editor CSS with custom media and custom properties

### PR DESCRIPTION
**Pull request by ataylorme**
## Description

Addresses issue #361. This uses [`gulp-tap`](https://www.npmjs.com/package/gulp-tap) to read CSS file contents in the middle of the stream during the `styles` task. 

If the file's path, relative to the CSS source directory, starts with `editor/` then utilities from [`postcss-custom-utils`](https://www.npmjs.com/package/postcss-custom-utils) are used to apply the custom media and custom properties to the file contents and the modified source file contents continue down the stream.

[This article](https://gulpjs.org/recipes/make-stream-from-buffer.html) suggests it might be possible to be more efficient by editing the file contents in memory.

The `@import` statements in the editor CSS source files for `custom-media.css` and `custom-properties.css` were removed as they are now applied directly to the file contents during the build process.

This was mostly a learning exercise for me to see if I _could_ do this. I still don't think we _should_ do this.

I think it might be easier to dynamically change `preserve` to `false` for editor CSS source files or maybe even use a different task all together for editor CSS source files

Maybe @jonathantneal is willing to help us find a solution to change the `:root` selector to `html` for specific CSS source files in the gulp task?

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by mor10** [comment]
Impressive! I need to think on this one for a bit.

**Comment by mor10** [comment]
Oops. Clicked the wrong button 😑

**Comment by jonathantneal** [comment]
There is a plugin to swap `:root` for `html`. https://github.com/jonathantneal/postcss-unroot

**Comment by ataylorme** [comment]
I'm closing this because we shouldn't take this approach.

**Pull request closed without merging**
