### PR TITLE
Fix is_amp_endpoint was called incorrectly

### PR DESCRIPTION
**Pull request by iliman**
## Description

Addresses issue #74

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by felixarntz** [comment]
Good catch! I'm wondering whether `wp` is the best hook to attach this too. At what point do we actually need the logic to be available? I think it should be initialized as late as possible, in order to not be unnecessary overhead for requests where it might not even be applicable (REST API etc.).

**Comment by iliman** [comment]
@felixarntz considering that the `wprig_lazyload_images()` function contains some hooks inside that must be executed on time(`wp_enqueue_scripts` is the earliest), we have the following corridor:

image

It turns out that `get_header` is the latest hook we can use. What do you think?

**Comment by felixarntz** [comment]
Thanks for the quick response @iliman, and for looking into the topic more closely! In that case, I think the `wp` hook is a solid choice. Let's move forward with this.

**Comment by bamadesigner** [comment]
Awesome! I'm going to merge into master since this is throwing notices. Thanks @iliman and @felixarntz.

**Pull request merged**
