### PR TITLE
Align .more-link with the content

### PR DESCRIPTION
**Pull request by benoitchantre**
## Description

Addresses issue #214 by setting this element the display property to `block` instead of `inline`.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by felixarntz** [comment]
@benoitchantre Thanks for this! I prefer your second approach, accomplishing this via correct markup instead of CSS changes. Would you mind updating the PR?

**Comment by benoitchantre** [comment]
@felixarntz Where should I place that code? In a new `Blocks` component?

**Comment by mor10** [comment]
The link breaks out of the layout because of an omission on my part. I simply didn't test properly for this scenario. The issue is really how we want to use this function in different templates. I personally think the "Continue reading" link should be on its own line even if it's in an excerpt so I'm leaning toward the suggestion of using the `the_content_more_link` filter to wrap it in a paragraph where appropriate.

@benoitchantre I'd like your thoughts on this: Where do you think the link should be in templates where it is displayed? Inline or on a separate line?

**Comment by felixarntz** [comment]
Can't we fix this in a more straightforward way, by adding `display: block;` to https://github.com/wprig/wprig/blob/v2.0/assets/css/src/content.css#L52 and https://github.com/wprig/wprig/blob/v2.0/assets/css/src/content.css#L68? We wanna make sure all child elements are block elements so that they can respect the margin/padding/max-width.

**Comment by benoitchantre** [comment]
> Can't we fix this in a more straightforward way, by adding `display: block;` [...]

@felixarntz That's actually what does the commit in this PR. The CSS selector only applies when the link is not wrapped by a paragraph.

**Comment by felixarntz** [comment]
@benoitchantre Yes, but the fix in this PR is very specific. I think it makes sense to fix it for _all_ content, everything that could possibly be part of that container. It's expected for all these things to be `display:block`, otherwise the rules I linked to in my comment won't have any effect, and that is why the more link for example is broken like that.

In other words: Your fix works, but I think it makes sense to fix it so that we don't run into it again with other things in the future.

**Comment by benoitchantre** [comment]
> I think it makes sense to fix it for all content, everything that could possibly be part of that container.

@felixarntz Thank you for the clarification. I think there's no downside to make the fix more general as proposed.

**Comment by mor10** [comment]
You have my blessing.

**Pull request merged**
