### PR TITLE
Better handling of copying files to prod theme bundle

### PR DESCRIPTION
**Pull request by ataylorme**
## Description

Addresses issue #273.

- Adds a `gulpRelativeDest` function utility which can be used in `gulp.dest` to save files relative to their location in the WP Rig source directory
- Moves the files to be copied to the poduction theme as-is (currently screenshot, readme, license, and `style.css`) to the default configuration
- Allows an `additionalFilesToCopy` array to be defined in `config.json` so additional items, such as fonts, can be copied
    - Another config item was added so that folks can update to the latest WP rig and use `additionalFilesToCopy` without worrying about keeping `filesToCopy` up to date in `config.json` if it changes in `config.default.json`

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ataylorme** [comment]
I did not add an entry to the changelog as this is cleaning up some of the larger source to production work, which is already in the changelog

**Comment by bamadesigner** [comment]
I checked out the branch, ran `npm install` and then ran `npm run bundle`. I got the following error:

`Error: File not found with singular glob: /Users/rachelcarden/Sites/localnyu.edu/app/public/wp-content/themes/wprig/undefined (if this was purposeful, use `allowEmpty` option)`

**Comment by bamadesigner** [comment]
I checked out the branch, ran `npm install` and then ran `npm run bundle`. I got the following error:

`Error: File not found with singular glob: LOCALPATH/wprig/undefined (if this was purposeful, use `allowEmpty` option)`

**Comment by ataylorme** [comment]
@bamadesigner can you try again now that `allowEmpty` is on for `gulp.src` for copying the additional files?

**Pull request merged**
