### PR TITLE
Fix mixed license and missing license URLs.

### PR DESCRIPTION
**Pull request by felixarntz**
## Description
Addresses issue #573 

## List of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by felixarntz** [comment]
@ataylorme It was mixed up, sometimes v2, sometimes v3. After our conversation yesterday, I've now updated it to be v3 everywhere instead of v2. cc @mor10

**Comment by mor10** [comment]
This one is interesting: It's really a bugfix for `master` and should be merged asap. I propose we merge and bump to `v2.0.1`

**Comment by mor10** [comment]
For reference, this was one of the sources for my decision to go v3 instead of v2: http://www.ifross.org/en/what-difference-between-gplv2-and-gplv3

**Comment by felixarntz** [comment]
@mor10 Makes sense. Let's merge this and release a quick v2.0.1.

**Pull request merged**
