### PR TITLE
Add gulp task to test theme

### PR DESCRIPTION
**Pull request by bamadesigner**
## Description
Wanted to have a task to just run a test.

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [X] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [X] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ataylorme** [comment]
The [php task](https://github.com/wprig/wprig/blob/6873e651d0e6fa4687c85104fb3485c49f23e5ee/gulp/php.js) simply runs code sniffing. So `npm run test`, which maps to `gulp testTheme`, which only calls `php`, will just run PHP code sniffing.

@bamadesigner I guess I am not clear on what you are wanting to test for. I expect a generic test command would run a suite of tests, such as PHP unit. Perhaps code sniffing too. Can you elaborate on your intent?

**Comment by felixarntz** [comment]
I would advise against integrating something like this in `package.json`. It is already possible to run these tests via `composer phpcs-dev`.

By convention `package.json` (or `npm do-something`) should be responsible for tasks related to the build workflow or anything client-side (JS/CSS), while `composer.json` (or `composer do-something`) should be responsible for server-side (PHP) tests of any kind.

**Comment by mor10** [comment]
Needs documentation?

**Comment by mor10** [comment]
What was the decision here? Merge, or remove from `package.json` and then merge?

**Comment by ataylorme** [comment]
The decision was to run code sniffing and unit testing through Composer - we should remove from `package.json`. `composer phpunit-dev` and `composer phpcs-dev` already exist so perhaps this should just be a documantation change.

**Comment by felixarntz** [comment]
@ataylorme I think we should close this PR and instead work on a Wiki article about the general development workflow, in addition to your gulp post (#284). The section on "Theme Configuration" you wrote there could be a sub-section of that development workflow article. I'd be happy to spin up the rest for it.

**Comment by felixarntz** [comment]
Bump: Can this be closed?

**Comment by felixarntz** [comment]
Closing this due to inactivity, and we agreed before that PHP tests should happen via Composer (e.g. `composer phpcs-dev`).

**Pull request closed without merging**
