### PR TITLE
Ensure that the theme requirements are met, otherwise bail and warn the user

### PR DESCRIPTION
**Pull request by felixarntz**
## Description
Addresses issue #50

This PR ensures that the theme requirements are checked, and if not met, the theme isn't initialized and the user receives a warning about this instead. The techniques implemented here have been already established by popular themes such as Twenty Seventeen.

The minimum required WP version is 4.5 (as used in `phpcs.xml.dist`).
The minimum required PHP version is 7.0 (as mentioned in `README.md`).

## List of changes
- [x] Bug fix (non-breaking change which fixes an issue)

* All functions have been moved out of `functions.php`. The functions that were previously part of it have been moved to separate files `inc/setup.php` and `inc/assets.php`. This allows to use modern PHP code in those files.
* Constants have been introduced for the minimum required WP and PHP versions.
* In order to catch these constants with the gulp replacing mechanism, support for that has been added. Since the value of the constant prefix can easily be determined automatically from `theme.slug` (and make it uppercase), it is not mandatory to provide that argument, but a developer still can if they prefer to use something else. A utility function `getThemeConfig()` takes care of that handling.
* In `functions.php` initially it is checked whether the two minimum requirements are met. If not, a new `inc/back-compat.php` file is loaded, and then the process bails, not initializing the theme any further.
* `inc/back-compat.php` contains logic to warn the user about the issue and keep the user from running into fatal errors possibly caused by the incompatibility.
* Going forward, we need to ensure that `functions.php` and `inc/back-compat.php` must remain parseable by PHP 5.2. The two files should generally not be edited, unless to add a new require statement to the `functions.php`. All other PHP files can use PHP 7.0 code as necessary.
* The `.travis.yml` and `phpcs.xml.dist` files have been adjusted to use PHP 7.0 as minimum version to test against.

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by mor10** [comment]
This looks useful, and would fit nicely into the full upgrade with v1.1. However, that would mean rewriting most of the Gulp features. Can you work with @ataylorme to get this PR aligned with the new Gulp process in 1.1?

**Comment by ataylorme** [comment]
@mor10 should the PR be made against `v1.1` rather than `master`? If so I am happy to help convert it

**Comment by ataylorme** [comment]
Went ahead and did the conversion for `v1.1`. It was easy enough to pull in @felixarntz's branch and clean up merge conflicts. @felixarntz can you review/test #69? Things looked good for me but I would like a +1

**Comment by felixarntz** [comment]
Closing in favor of #69 which is the more up-to-date follow-up for this one.

**Pull request closed without merging**
