### PR TITLE
Add methods to check template sidebars status

### PR DESCRIPTION
**Pull request by benoitchantre**
## Description

Addresse issue #461, related to #331.

Sets a clear relation between templates and sidebars. Adds methods to check all active sidebars for the current template.

The visibility of `get_template_sidebars()` is set to `private` to ease its future replacement. Ideally, we  should have a programmatic way of knowing which templates/pages have sidebars.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by mor10** [comment]
Calling @felixarntz

**Comment by mor10** [comment]
> Ideally, we should have a programmatic way of knowing which templates/pages have sidebars.

This is a limitation of WordPress themes in general. If we could know what components were used in a template before it was rendered, a lot of what we do would be way easier.

**Comment by benoitchantre** [comment]
Ping @felixarntz.

**Comment by benoitchantre** [comment]
As discussed with @felixarntz during Contributor Day, this PR can be closed.
Related: #533.

**Pull request closed without merging**
