### PR TITLE
Always copy, and run string replacement, on style.css

### PR DESCRIPTION
**Pull request by ataylorme**
## Description

Addresses issue #350. Always copy, and run string replacement, on `style.css`

Adds a new task `prodStringReplace`, which copies files requirted for the bundled theme but not created in a build step to the production theme and runs string replacement on them.

Rename `prodFinish` to `prodCompress` as the task creates the `.zip` of the production bundle.

Remove `style.css` from `filesToCopy` in the default config as it is now handled with the new `prodStringReplace` task.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by Drivingralle** [comment]
Hey!

I have checked out the _string-replace-style-css_ branch.
Run `npm run rig-init`

`> wprig@2.0.0 rig-init /WP-Rig/app/public/wp-content/themes/wprig
> npm install && composer install


> fsevents@1.2.7 install /WP-Rig/app/public/wp-content/themes/wprig/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/WP-Rig/app/public/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> gifsicle@4.0.1 postinstall /WP-Rig/app/public/wp-content/themes/wprig/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall /WP-Rig/app/public/wp-content/themes/wprig/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@5.1.0 postinstall /WP-Rig/app/public/wp-content/themes/wprig/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
added 1463 packages from 677 contributors and audited 18796 packages in 16.963s
found 10 vulnerabilities (3 low, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 36 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.4.2): Downloading (100%)        - Installing dealerdirect/phpcodesniffer-composer-installer (v0.4.4): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.2.0): Loading from cache
  - Installing antecedent/patchwork (2.1.8): Loading from cache
  - Installing brain/monkey (2.2.0): Loading from cache
  - Installing phpcompatibility/php-compatibility (9.1.0): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.13): Loading from cache
  - Installing wp-coding-standards/wpcs (2.0.0): Loading from cache
dealerdirect/phpcodesniffer-composer-installer suggests installing dealerdirect/qa-tools (All the PHP QA tools you'll need)
phpcompatibility/php-compatibility suggests installing roave/security-advisories (dev-master || Helps prevent installing dependencies with known security issues.)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../wp-coding-standards/wpcs/
`

Run `npm run build`

`> wprig@2.0.0 build /WP-Rig/app/public/wp-content/themes/wprig
> gulp buildDev

[11:08:24] Requiring external module @babel/register
[11:08:25] Using gulpfile /WP-Rig/app/public/wp-content/themes/wprig/gulpfile.babel.js
[11:08:25] Starting 'buildDev'...
[11:08:25] Starting 'php'...
[11:08:25] Starting 'images'...
[11:08:25] Starting 'scripts'...
[11:08:25] Starting 'translate'...
[11:08:25] Starting 'styles'...
[11:08:26] gulp-imagemin: Minified 0 images
[11:08:26] Finished 'images' after 1.09 s
[11:08:28] Finished 'scripts' after 2.83 s
[11:08:29] Finished 'translate' after 4.22 s
[11:08:30] Finished 'styles' after 4.62 s
[11:08:30] Starting 'editorStyles'...
[11:08:30] Finished 'editorStyles' after 428 ms
[11:08:41] Finished 'php' after 16 s
[11:08:41] Finished 'buildDev' after 16 s
`

And one more time with the following config:
`{
  "theme": {
    "slug": "my-theme",
    "name": "My own theme",
    "author": "WP Rig Tester"
  },
  "dev": {
    "browserSync": {
      "live": false
    }
  }
}
`

Booth times no theme got generated. Therefore I couldn't test if the details from the config get replaced in the style.css

**Comment by ataylorme** [comment]
> Run `npm run build`

@Drivingralle `npm run build` will do a one-time build of the dev theme (without watching for changes). `npm run bundle` is to generate a production version. Can you try again with `npm run bundle`.? Based on your posted config that should generate the production theme at `wp-content/themes/my-theme`.

**Comment by Drivingralle** [comment]
I run the follwoing commands `git pull` and `npm run rig-init`

```
> wprig@2.0.0 WP-Rig/app/public/wp-content/themes/wprig
> npm install && composer install

audited 18796 packages in 5.743s
found 10 vulnerabilities (3 low, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../wp-coding-standards/wpcs/,../../phpcompatibility/php-compatibility/
```

Followed by `npm run bundle`:
```
> wprig@2.0.0 bundle WP-Rig/app/public/wp-content/themes/wprig
> NODE_ENV=production gulp bundleTheme

[11:12:32] Requiring external module @babel/register
[11:12:35] Using gulpfile WP-Rig/app/public/wp-content/themes/wprig/gulpfile.babel.js
[11:12:35] Starting 'bundleTheme'...
[11:12:35] Starting 'prodPrep'...
[11:12:35] Creating the production theme directory WP-Rig/app/public/wp-content/themes/my-theme
[11:12:35] Finished 'prodPrep' after 37 ms
[11:12:35] Starting 'php'...
[11:12:35] Starting 'scripts'...
[11:12:35] Starting 'images'...
[11:12:36] Starting 'styles'...
[11:12:37] gulp-imagemin: Minified 1 image (saved 20 B - 22.7%)
[11:12:38] Finished 'images' after 2.82 s
[11:12:38] Finished 'scripts' after 2.93 s
[11:12:40] Finished 'styles' after 3.72 s
[11:12:40] Starting 'editorStyles'...
[11:12:40] Finished 'editorStyles' after 405 ms
[11:12:51] Finished 'php' after 16 s
[11:12:51] Starting 'translate'...
[11:12:52] Finished 'translate' after 247 ms
[11:12:52] Starting 'prodStringReplace'...
[11:12:52] Finished 'prodStringReplace' after 6.1 ms
[11:12:52] Starting 'prodCompress'...
[11:12:52] Finished 'prodCompress' after 101 ms
[11:12:52] Finished 'bundleTheme' after 17 s
```

Theme gets generated. As folder and archive.

Style.css file gets genereated and contains following header:
```
/*!
Theme Name: My own theme
Theme URI: https://github.com/wprig/wprig/
Author: The My own theme Contributors
Author URI: https://github.com/wprig/wprig/
Description: A progressive theme development rig for WordPress.
Version: 2.0.0
License: GNU General Public License v3 or later
License URI: LICENSE
Text Domain: my-theme
Tags: translation-ready

This theme, like WordPress, is licensed under the GPL.
Use it to make something cool, have fun, and share
what you've learned with others.
*/
```

Theme name and slug are fine. BrowserSync didn't start as config says.
**Theme author doesn't match config file.**

**Comment by ataylorme** [comment]
@Drivingralle feel free to edit the `Author` field (and anything else except perhaps `Theme Name`) in `style.css`.

The string replacement is very specific, only replacing exact match strings from the defaults. The main purpose is to update PHP namespaces, function names, etc. rather than generate a perfect `style.css` file.

**Comment by Drivingralle** [comment]
@ataylorme For me it feels broken it I can write something inside the config file but it doesn't get tranlated into the generated file.
I would say if it doesn't translate don't but it into the config file.

**Comment by ataylorme** [comment]
> Theme name and slug are fine. BrowserSync didn't start as config says.

Browser Sync does not start when building the production theme. It will run when WP Rig is in dev mode with `npm run dev`.

> Theme author doesn't match config file.

I think I understand what is happening. The order we run string replace is causing `WP Rig` in `The WP Rig Contributors` to be replaced first. Then, when the author replacement runs there is not longer a match because the author text is now `The My own theme Contributors` and doesn't match `The WP Rig Contributors` anymore so it is not replaced.

I updated the process to replace the Author first and it is working as expected now for me. @Drivingralle can you test again with this change?

**Comment by Drivingralle** [comment]
@Drivingralle Work fine now

**Pull request merged**
