### PR TITLE
Make sure content.css always loads for content

### PR DESCRIPTION
**Pull request by bamadesigner**
## Description

content.css has styles for the content area but wasn't being loaded on pages that had no post content to fill the content area. Basically these pages still need the content.css markup for the surrounding DOM.

This PR ensures its loaded for all content areas, whether or not posts exist.

The following templates should be tested:

- 404.php
- index.php
- archive.php
- attachment.php
- category.php
- custom page template
- custom post template
- front-page.php
- page.php
- search.php
- single.php
- singular.php

Addresses issue #138.

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [X] This pull request relates to a ticket.
- [X] My code is tested.
- [ ] I want my code added to WP Rig.

### CODE REVIEW

**Comment by mor10** [comment]
`v2.0` was just updated (and basically rewritten). Please sync with the upstream branch, test the new code to see if your proposal is still valid, and if so update your PR. And yes, I know it's you Rachel, I'm just dotting my ts and crossing my is

**Comment by mor10** [comment]
bump bump bump

**Comment by felixarntz** [comment]
Where is this at? Should be either adjusted to apply against `v2.0` and merged, or punted soon.

**Comment by benoitchantre** [comment]
#291 is ready to merge, fixes the same issue, plus other minor alignments issues.

**Comment by felixarntz** [comment]
After merging I noticed this was missing `500.php` and `offline.php`, which I fixed in 68979f8e97d7531ecfc4d5cfdcff3c86e426b2ec

**Comment by bamadesigner** [comment]
@felixarntz I was in the middle of fixing all of that when you merged. :)

**Comment by bamadesigner** [comment]
@felixarntz I submitted the cleanup here: https://github.com/wprig/wprig/pull/307

**Pull request merged**
