### PR TITLE
PHP 8.1 Compatibility

### PR DESCRIPTION
**Pull request by robruiz**
## Description

Addresses issue #

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [ ] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [ ] I want my code added to WP Rig.

### CODE REVIEW

**Comment by websupergirl** [comment]
I am getting 3 codesniffer issues on the PHP 7.4 / M1 build:

```
[15:31:53] PHP Code Sniffer found a problem in /Users/nikole/Desktop/wprig/inc/Theme.php
E 1 / 1 (100%)
    
    FILE: /Users/nikole/Desktop/wprig/inc/Theme.php
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     159 | ERROR | [x] Each array item in a multi-line array declaration
         |       |     must end in a comma
         |       |     (WordPress.Arrays.CommaAfterArrayItem.NoComma)
    ----------------------------------------------------------------------
    PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    ----------------------------------------------------------------------
    
    Time: 96ms; Memory: 12MB
    
[15:31:53] PHP Code Sniffer found a problem in /Users/nikole/Desktop/wprig/inc/Base_Support/Component.php
E 1 / 1 (100%)
    
    FILE: /Users/nikole/Desktop/wprig/inc/Base_Support/Component.php
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     94 | ERROR | [x] Functions must not contain multiple empty lines in
        |       |     a row; found 2 empty lines
        |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EmptyLines)
    ----------------------------------------------------------------------
    PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    ----------------------------------------------------------------------
    
    Time: 93ms; Memory: 12MB
    
[15:31:57] PHP Code Sniffer found a problem in /Users/nikole/Desktop/wprig/inc/Theme_Supports/Component.php
E 1 / 1 (100%)
    
    FILE: /Users/nikole/Desktop/wprig/inc/Theme_Supports/Component.php
    ----------------------------------------------------------------------
    FOUND 2 ERRORS AFFECTING 2 LINES
    ----------------------------------------------------------------------
     18 | ERROR | Missing member variable doc comment
        |       | (Squiz.Commenting.VariableComment.Missing)
     43 | ERROR | Missing doc comment for function
        |       | wp_rig_add_theme_supports()
        |       | (Squiz.Commenting.FunctionComment.Missing)
    ----------------------------------------------------------------------
    
    Time: 76ms; Memory: 12MB
```

**Comment by robruiz** [comment]
@websupergirl  - you do have make sure that if you are not installing a new instance of wp rig from scratch that you will need to run "composer upgrade" to get the new version of php_codesniffer. However, brand new installations of WP Rig should work just fine.

**Comment by websupergirl** [comment]
@robruiz I did install from scratch (as I always do with testing) but I did have to change the PHP version during the build (as I had said in the issue). Without changing the PHP version during the build and cloning it fresh again, I still get

```
    FILE: /Users/nikole/new/wprig/inc/Base_Support/Component.php
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     94 | ERROR | [x] Functions must not contain multiple empty lines in
        |       |     a row; found 2 empty lines
        |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EmptyLines)
    ----------------------------------------------------------------------
    PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    ----------------------------------------------------------------------
    
    Time: 90ms; Memory: 12MB
```
on PHP 7.4.32 with the M1. (PHP 8 is still not working.)

Just FYI, hope this helps.

**Comment by robruiz** [comment]
Would you mind fixing that and submitting a PR?

**Pull request merged**
