### PR TITLE
Merge master into v2.0 branch

### PR DESCRIPTION
**Pull request by felixarntz**
Currently, the `v2.0` branch is a few commits behind `master`. That shouldn't be the case, this PR simply merges the not yet included changes from `master` into `v2.0`.

### CODE REVIEW

**Comment by felixarntz** [comment]
@mor10 Something must have went wrong there, as `v2.0` is still the 5 commits behind `master`.

**Comment by mor10** [comment]
I'll take a closer look.

**Comment by mor10** [comment]
Weird. I think they might have been dislocated because I used "Squash and merge" rather than just "Merge". Anyway, it looks to me like all the updates are in the `v2.0` branch so it should be OK, at least from a pure code perspective. Not entirely sure how (and whether there's any need) to "fix" this if the only issue is a disconnect within Git, not actual code missing. Thoughts @felixarntz?

**Comment by felixarntz** [comment]
@mor10 It is just confusing. I agree there's no code-wise benefit, but I think we should fix it - I guess by simply merging instead of squashing and merging. Obviously low priority, but in the future people might be wondering why there is something in v1 that is not in v2.

**Comment by mor10** [comment]
Pull down the latest version of v2.0. I did some updates and it looks to me like the changes were baked in. Master has also diverged from v2.0 so the problem is no longer "real" if that makes any sense.

**Pull request merged**
