### PR TITLE
Add phpcbf to Composer scripts

### PR DESCRIPTION
**Pull request by ataylorme**
## Description

Addresses issue #72. `composer run-phpcbf` can now be used to run PHPCBF installed via Composer.

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [x] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by mor10** [comment]
This is @felixarntz territory.

**Comment by bamadesigner** [comment]
While testing, I ran `composer run-phpcs`. FYI: it finds issues in minified CSS.

**Comment by bamadesigner** [comment]
While testing, I ran composer run-phpcs. FYI: it finds issues in minified CSS. So then running `composer run-phpcbf` fixes issues in 2 minified CSS files.

**Comment by felixarntz** [comment]
@bamadesigner That's odd. Can you open a bug for this separately?

**Comment by mor10** [comment]
I assume it's the same issues that pop up if you do a dev run?

```
_reset.css
 315    ✖  Expected selector "::-webkit-file-upload-button" to come before selector ":root"   no-descending-specificity

global.css
 242    ✖  Expected selector "blockquote" to come before selector ".entry-content > blockquote"   no-descending-specificity
```

**Comment by ataylorme** [comment]
At least that validates that `phpcs` and `phpcbf` are working properly 😆

**Comment by felixarntz** [comment]
Yep, I got these too.

**Comment by mor10** [comment]
I'll make a separate issue for those. It's a CSS thing which may be a Stylelint config issue rather than an actual issue.

**Comment by bamadesigner** [comment]
Nevermind. I re-built everything and it went away so could just be an environment issue between branches and updates and such.

**Comment by bamadesigner** [comment]
The files it was "fixing" were empty files so yea.

**Pull request merged**
