### PR TITLE
Silences the PHPCS. But the comment lines 186-188 in inc/Nav_Menus/Co…

### PR DESCRIPTION
**Pull request by erdmann040**
Silences the PHPCS. But the comment lines 186-188 in inc/Nav_Menus/Component.php are in need of improvement.

## Description
PHPCS Complaints 

## List of changes
Just added esc_html__(), esc_html() function and changed the order off `use` statements to silence the PHP code sniffer

### CODE REVIEW

**Comment by erdmann040** [comment]
Now I have synchronised my private github fork and checked out the develop branch.

It seams i have the latest version:

```
jan@desktop wprig develop *$ git log -1
commit 03d398d69bd0ec6592c9440b9ff306c930ddd854 (HEAD -> develop, origin/develop)
Author: robruiz <rob.c.ruiz@gmail.com>
Date: Wed Feb 21 00:54:23 2024 -0600

    run phpcbf
```

```
jan@desktop wprig develop *$ git pull
Already up to date.

```

But when I run Wprig via npm I don't see any any code sniffer complaints. 

```
jan@desktop wprig develop *$ npm run dev

> wprig@2.3.1 dev
> gulp

[14:07:17] Requiring external module @babel/register
[14:07:19] Using gulpfile ~/local-sites/wprig-pull-request/app/public/wp-content/themes/wprig/gulpfile.babel.js
[14:07:19] Starting 'default'...
[14:07:19] Starting 'cleanCSS'...
[14:07:19] Finished 'cleanCSS' after 19 ms
[14:07:19] Starting 'cleanJS'...
[14:07:19] Finished 'cleanJS' after 5.2 ms
[14:07:19] Starting 'php'...
[14:07:19] Starting 'images'...
[14:07:19] Starting 'scripts'...
[14:07:19] Starting 'styles'...
[14:07:20] gulp-imagemin: Minified 0 images
[14:07:20] Finished 'images' after 1.65 s
[14:07:23] Finished 'scripts' after 4.05 s
[14:07:24] Finished 'styles' after 5.6 s
[14:07:24] Starting 'editorStyles'...
[14:07:25] Finished 'editorStyles' after 483 ms
[14:07:41] Finished 'php' after 23 s
[14:07:41] Starting 'serve'...
[14:07:41] Finished 'serve' after 25 ms
[14:07:41] Starting 'watch'...
[Browsersync] Proxying: http://wprig-pull-request.local
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:8187
    External: http://192.168.178.2:8187
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 --------------------------------------

```

Do you have any idea what I am doing wrong?

**Comment by robruiz** [comment]
What version of PHP are you using? I'd like to know why you are not getting
any but I am. Could help lead us to the solution. I'm getting a ton of
them. Glad it cleans it up for some people though.

**Comment by erdmann040** [comment]
So the error is on my side, Sorry! I just saw that the code sniffer is not working properly and does not mark violations with the typical red underlines.

I have experimented a lot with settings, plugins and integrated tools under VS Code. I get a warning when starting VS Code:  

"phpcs: The referenced sniff "PHPCompatibility" does not exist"

```
jan@desktop ~$ php -v
PHP 8.2.15 (cli) (built: Jan 16 2024 12:19:32) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.15, Copyright (c), by Zend Technologies
```

**Comment by robruiz** [comment]
I use PHPStorm. However, sniffs real-time in the editor vs sniffs during
the build are kind of separate I've noticed. If you look in the Gulp
directory, you can see the process it runs when you run npm run dev, it
spins up gulp-phpcs. That's where I was pulled towards last night in terms
of the warnings I was seeing.

**Pull request merged**
