### PR TITLE
Improve gulp error logging

### PR DESCRIPTION
**Pull request by ataylorme**
## Description
Improve sass error logging by making use of [`gulp-plumber`](https://www.npmjs.com/package/gulp-plumber) and [`gulp-notify`](https://www.npmjs.com/package/gulp-notify) to log sass errors as operating system notifications.

Addresses issue #128 

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ataylorme** [comment]
@mor10, @bamadesigner or @felixarntz any of you want to test this as well? If not, objections to me merging?

**Comment by ataylorme** [comment]
@maximls thank you for testing!

**Comment by felixarntz** [comment]
@ataylorme I tested it and didn't encounter any issues, I would just like to know more on what this exactly does and what your thoughts behind implementing this are. When I ran it locally and broke some CSS, I don't think I saw anything being different from before - maybe that's just my memory, but it would be great if you could clarify.

**Comment by maximls** [comment]
@felixarntz I originally created the issue #128 to improve SASS error logging. If you break SASS then you will see the error in the log output. I'll let Andrew share his thoughts on implementation.

**Comment by ataylorme** [comment]
@felixarntz `gulp-notify` makes is to that sass errors are logged to system notifications, not just printed in the terminal, for better visibility.

**Pull request merged**
