### PR TITLE
Headings in _typography.css not using css variables

### PR DESCRIPTION
**Pull request by ehowey**
## Description

Addresses issue #462 
Quick fix of the heading color as it was not using the `color: var(--global-font-color);` but rather was specifying a HEX color value.  I assume this is a bug unless there is some reason this couldn't be used for heading colors.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [ ] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ehowey** [comment]
As a side note both .site-title and .site-description are also specifying hex values for the font color although I wonder if this was intentional?

**Comment by ehowey** [comment]
@mor10 Would you prefer I leave this PR as is or do as Benoit suggested and remove the color value entirely?

**Comment by bamadesigner** [comment]
@ehowey Hi! Yes, let's go ahead and just remove the color selector since it will just inherit global styles. Thanks!

**Comment by ehowey** [comment]
Done - thanks for helping a relative git newbie like me through some of my first PRs!

**Pull request merged**
