### PR TITLE
added 'deps' to css files array

### PR DESCRIPTION
**Pull request by Spleeding1**
## Description

Addresses issue #

Added 'deps' array key to Styles/Component.php to allow for wp_enqueue_style dependencies.

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [X] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [X] I want my code added to WP Rig.

### CODE REVIEW

**Comment by dthenley** [comment]
@Spleeding1 is there a good use case I can try this out with.

**Comment by Spleeding1** [comment]
styles-b.css depends on styles-a.css, so styles-a.css has to load first

**Comment by Spleeding1** [comment]
or probably better class in style-b.css overwrites style-a.css. It's built into WordPress enqueue but never implemented in WP Rig. This implements it.

**Comment by dthenley** [comment]
After reviewing this and diving into the code a bit more it looks like dependencies for preloaded stylesheets doesnt exist just yet. When we preload the stylesheet is not traditionally enqueueing the stylesheet via wordpress `wp_enqueue_style` function rather it is creating a `<link>` element as seen here https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload.

**Comment by Spleeding1** [comment]
It comes into play on lines 124 of Component.php

**Comment by dthenley** [comment]
@Spleeding1 Haha I'm pretty foolish right now. Because i've been dealing with strictly wordpress and havent even evaluated how css files are included in an html document for a while here i was thinking css files were imported using `<style href="...">` and not `<link>` 🤦‍♂️. But I am still having issues with getting this to work with the style component. If you can come up with a use case so we can get it tested it out i think it would be a great addition to the code.

**Comment by Spleeding1** [comment]
I will. Thanks for all of the work you are putting in. Believe me, I know what it is like to stare at something and have it be something stupid as to why it wasn't working

**Pull request merged**
