### PR TITLE
Fix visual regressions caused by invalid CSS values

### PR DESCRIPTION
**Pull request by benoitchantre**
## Description

Addresses issue #171.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] My code is tested.
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ataylorme** [comment]
@benoitchantre looks like this PR is against the `master` branch. Can you update the base to be the `v2.0` branch?

**Comment by benoitchantre** [comment]
> @benoitchantre looks like this PR is against the `master` branch. Can you update the base to be the `v2.0` branch?

@ataylorme Done :-)

**Comment by ataylorme** [comment]
Thanks for another PR @benoitchantre

**Comment by benoitchantre** [comment]
Happy to contribute. Thank you for your work @ataylorme (same thing for others contributors).

**Comment by ataylorme** [comment]
If you end up using `v2.0` on a project we are looking for testimonials/case studies from the community so please reach out if that interests you.

**Comment by benoitchantre** [comment]
> If you end up using `v2.0` on a project we are looking for testimonials/case studies from the community so please reach out if that interests you.

Noted. I'll certainly use `v2.0` for the next project.

**Pull request merged**
