### PR TITLE
Clarify naming of wprig development folder in the installation process

### PR DESCRIPTION
**Pull request by ehowey**
## Description
Addresses issue #430 
Clarification of the folder name restrictions when installing wprig.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [ ] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by ataylorme** [comment]
@ehowey thank you for the pull request! Do you think it makes sense to add something like "for this reason, we suggest having the directory name of the WP Rig development theme be `wprig`".

**Comment by ehowey** [comment]
I am hesitant about this...part of where this came up for me was in having multiple installs of wprig in one local wordpress install.  This started happening for me when I was flipping between v1.x and v2.0 - I got scared that something would break if I messed up the folder naming convention...I would have preferred to just do something like 'excalibur-dev' and then if needed 'excalibur-dev-2', etc. 

I also ran into an odd issue with npm run rig init when continuing to use the same folder name.  I should probably test this in a clean install and see more about what happened, if I recall correctly the rig init process didn't properly download all of the dependencies, it almost seemed as if it thought they were cached already or something.  What I did to make this happen was move my 'wprig' folder to a new directory (backed it up), and then download a fresh copy of 2.0 in folder 'wprig', ran `npm run rig init`.  This issue fixed for me if I renamed the folder to something like 'wprig3'...what I was doing then was renaming the folder, running the `npm run rig init` command, and then renaming the folder back to `wprig`.  

What if the sentence was "The default development folder name is `wprig`?

**Comment by ataylorme** [comment]
Interesting, I hadn't considered folks having multiple copies of WP Rig. It makes sense during a migration period from `1.x` to `2.x`. Thank you for sharing more details about your usage.

**Comment by benoitchantre** [comment]
> Interesting, I hadn't considered folks having multiple copies of WP Rig

Here's my setup: I have multiple copies of WP Rig (one for each theme based on WP Rig). They are located in an external directory where I have all my custom themes and plugins. Then, they are symlinked as `wprig` into the dev environment.

When I run `npm run bundle`, the bundle is located in `wp-content/themes/`. It works well.

**Comment by ataylorme** [comment]
@benoitchantre are you using more than one WP Rig based theme per project? As WordPress can only have one theme active at a time, as opposed to many active plugins, my expectation is that there will be one WP Rig theme per project in most cases.

If there is a use case for actively developing two themes (or more) with WP Rig at the same time I would like to know more details.

**Comment by GitaStreet** [comment]
@ataylorme 

"If there is a use case for actively developing two themes (or more) with WP Rig at the same time I would like to know more details."

I work on various projects, and also do testing and learning from various starter themes and frameworks. 

For work on localhost I use a WordPress Multisite installation. Just makes it easier and quicker to setup a subfolder for new tests. 

Also I sometimes found difficulties making the build process work with WP Rig - so it was relevant to keep the one that work - as well as try out the new versions as they appear :-)

**Comment by benoitchantre** [comment]
> are you using more than one WP Rig based theme per project?

@ataylorme No. I setup a dev environment for each project (with Local by Flywheel). I work on client projects, but if I had to work on premium themes, I would probably adopt the same strategy.

In the case I had to keep many WP Rig projects inside the same environment, I would try (not tested) to use a name like `wprig-themeslug` for folder name, to avoid name collision.

**Comment by ehowey** [comment]
Out of curiosity tonight I tried to reproduce the error I mentioned above with multiple iterations of the folder `wprig` in the same local wordpress install - it seemed similar to what was reported here today: https://github.com/wprig/wprig/issues/440

I couldn't get the error to happen again, at least on my first try, I basically did two fresh installs of wprig in a clean local dev environment.  Both in a folder named `wprig`.  It worked fine.  Whatever the bug was that we both encountered here must be more limited.

**Comment by benoitchantre** [comment]
> Here's my setup: I have multiple copies of WP Rig (one for each theme based on WP Rig). They are located in an external directory where I have all my custom themes and plugins. Then, they are symlinked as wprig into the dev environment.
>
> When I run npm run bundle, the bundle is located in `wp-content/themes/`. It works well.

Not tested enough: it doesn't work, sorry. 🤦‍♂

Themes that are located in an external directory need a directory name like `wprig-themeslug` to prevent a name collision when you create the bundle with `npm run bundle`. If you use a `symlink` the bundle will be created your external directory, not in `wp-content/themes/`.

> In the case I had to keep many WP Rig projects inside the same environment, I would try (not tested) to use a name like `wprig-themeslug` for folder name, to avoid name collision.

It works, but you see multiple themes named `WP Rig`. #427 will solve that inconvenient.

**Comment by benoitchantre** [comment]
> If there is a use case for actively developing two themes (or more) with WP Rig at the same time I would like to know more details.

I'm testing that: I have specific environment for each of my projects (client work) and an environment setup with the Theme Unit Test data.

Even if it is not complicated and long to create a new environment with the Theme Unit Test data, it's easier and faster to keep only one.

When I start to work on the theme, I start in the environment setup with the Theme Unit Test data. After some time, when common styles are defined, I work in the project environment where I have a content closer to the reality, additional plugins and the need for additional styles.

**Comment by mor10** [comment]
I'm merging this. We can review as part of the documentation process.

**Pull request merged**
