### PR TITLE
Fix stylelint comments

### PR DESCRIPTION
**Pull request by benoitchantre**
## Description

Addresses issue #445.

Removes comments to disable stylelint when they were not needed.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by benoitchantre** [comment]
Thank you @ataylorme for the review and your research. I have removed the comments to disable styelint for fonts.

> Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means most punctuation characters and digits at the start of each token must be escaped in unquoted font family names. 

https://www.w3.org/TR/CSS2/fonts.html#propdef-font-family

To keep stylelint is happy, font family names of one word need to be quoted.

**Comment by ataylorme** [comment]
@benoitchantre are you still getting the `value-keyword-case` warning from stylelint about font names?

**Comment by benoitchantre** [comment]
> are you still getting the `value-keyword-case` warning from stylelint about font names?

@ataylorme Yes, when I don't use quotes with single word font familiy names.

**Comment by ataylorme** [comment]
> To keep stylelint is happy, font family names of one word need to be quoted.

I don't think updating the CSS to have quotes around single-word font names will hurt. Should there be a new PR or do you want to update in this one?

**Comment by benoitchantre** [comment]
> Should there be a new PR or do you want to update in this one?

There's nothing to change. Font family names are already quoted.

**Comment by ataylorme** [comment]
I can close this out but perhaps we should update documentation. @mor10 want to add a section to the CSS wiki article?

**Comment by benoitchantre** [comment]
@ataylorme I think this should not be closed, the remaining changes are valid (removal of useless stylint comments).

**Pull request merged**
