### PR TITLE
Remove duplicate CSS that is causing stylelint error.

### PR DESCRIPTION
**Pull request by teddarling**
## Description
Addresses issue #401
Remove duplicate CSS entries in /assets/css/src/editor/editor-styles.css

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [ ] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

### CODE REVIEW

**Comment by mor10** [comment]
We just merged #390 which impacts this PR. @benoitchantre may have input here.

**Comment by benoitchantre** [comment]
#401 is now fixed by #390.

@mor10 I see now that I missed a few things in #390. I'll open a follow-up PR in a few minutes.

**Comment by teddarling** [comment]
I have pulled the changes to include #390. 

It has resolved the issue in the original file at /assets/css/src/editor/editor-styles.css

However, it has introduced a new linting error in /assets/css/src/content.css as per this lint message:

```
assets/css/src/content.css
264:1   ⚠  Unexpected duplicate selector ".alignwide", first used at line 176 (no-duplicate-selectors) [stylelint]
268:1   ⚠  Unexpected duplicate selector ".alignfull", first used at line 180 (no-duplicate-selectors) [stylelint]
```

@benoitchantre, please consider with your follow-up PR.

**Comment by benoitchantre** [comment]
> please consider with your follow-up PR.

@teddarling Fixed in #406.

**Pull request closed without merging**
